---
- name: Mise à jour du conteneur (comme dans le script)
  apt:
    update_cache: yes
    cache_valid_time: 3600
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Installation des paquets nécessaires (exactement comme le script)
  apt:
    name: "{{ debian_packages }}"
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive
  notify: restart apache