---
- name: Installer EPEL repository
  dnf:
    name: epel-release
    state: present
  ignore_errors: yes

- name: Initialiser MariaDB pour Rocky Linux
  shell: |
    if [ ! -d /var/lib/mysql/mysql ]; then
      mysql_install_db --user=mysql --datadir=/var/lib/mysql
    fi
    chown -R mysql:mysql /var/lib/mysql
  ignore_errors: yes

- name: Installer les paquets Rocky Linux
  dnf:
    name: "{{ redhat_packages }}"
    state: present
  ignore_errors: yes
