---
- name: restart apache
  command: service apache2 restart
  when: ansible_os_family == 'Debian'
 
- name: reload apache
  command: service apache2 reload
  when: ansible_os_family == 'Debian'
 
- name: restart httpd
  shell: /usr/sbin/httpd -DFOREGROUND &
  async: 10
  poll: 0
  when: ansible_os_family == 'RedHat'
 
- name: restart mariadb
  shell: mysqld_safe --datadir=/var/lib/mysql &
  async: 10
  poll: 0